inherit_from: .rubocop_todo.yml
Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/**/*
    - vendor/**/*
    - node_modules/**/*
IfUnlessModifier:
  Enabled: false
Loop:
  Enabled: false
ClassLength:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
SignalException:
  Enabled: false
Documentation:
  Enabled: false
DotPosition:
  Enabled: false
RedundantBegin:
  Enabled: false
EachWithObject:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - config/environments/production.rb
Lint/UselessAssignment:
  Exclude:
    - config.rb
Lint/UnifiedInteger: # enable this when we switch to Ruby 2.4
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - Guardfile
    - Vagrantfile
    - config/routes.rb
    - lib/tasks/**/*
    - spec/**/*
Metrics/PerceivedComplexity:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/MixinUsage:
  Exclude:
    - bin/*
Style/NumericLiterals:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
